# Generated by Django 5.0.1 on 2024-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('F', 'Female')], max_length=12),
        ),
    ]
